export const ContextKeys = {
  isInitialized: 'demo-time.isInitialized',
  showWelcome: 'demo-time.showWelcome',
  previousEnabled: 'demo-time.previousEnabled',
  presentation: 'demo-time.presentation',
  showTimer: 'demo-time.showTimer',
  countdown: 'demo-time.countdown',
  hasCodeHighlighting: 'demo-time.hasCodeHighlighting',
  hasNotes: 'demo-time.hasNotes',
  isSlide: 'demo-time.isSlide',
  hasPreviousSlide: 'demo-time.hasPreviousSlide',
  isHackerTyper: 'demo-time.isHackerTyper',
  isWaitingForNext: 'demo-time.isWaitingForNext',
  isSponsor: 'demo-time.isSponsor',
};
