import { DEFAULT_FONT_FAMILY } from './constants';
import { PREVIEW_BASE_CSS } from './previewBase.generated';

/**
 * The preview iframe renders a slide *exactly* the way the real extension does:
 *
 *  1. PREVIEW_BASE_CSS – the REAL compiled preview.css the extension webview
 *     ships (real Tailwind preflight + theme variables + structural rules),
 *     generated by scripts/compile-themes.mjs so it can never drift.
 *  2. ENVIRONMENT_CSS  – the few styles the slide gets from outside preview.css
 *     at runtime: VS Code's webview body font and the Tailwind utility classes
 *     MarkdownPreview.tsx puts inline on `.slide` / `.slide__container`.
 *
 * The generated theme CSS then layers on top, just like a real custom theme.
 */

const ENVIRONMENT_CSS = `
/* VS Code webview default body styles (forwarded vars resolve in VS Code). */
body {
  font-family: var(--vscode-font-family, ${DEFAULT_FONT_FAMILY});
  font-size: var(--vscode-font-size, 13px);
  color: var(--vscode-foreground, #cccccc);
}

/* Inline utilities MarkdownPreview.tsx sets on the slide wrappers:
   .slide:            relative w-full h-full overflow-hidden
   .slide__container: absolute top-[50%] left-[50%] w-[960px] h-[540px]
                      + translate(-50%,-50%) scale(...) inline transform.
   The transform also makes .slide__container the containing block + stacking
   context for the fixed-position .slide__video, exactly as in the extension. */
.slide { position: relative; width: 960px; height: 540px; overflow: hidden; }
.slide__container {
  position: absolute;
  top: 50%;
  left: 50%;
  width: 960px;
  height: 540px;
  transform: translate(-50%, -50%) scale(1);
}
.slide__image_left, .slide__image_right { width: 100%; height: 100%; }
`;

/**
 * Assemble a full HTML document for the preview iframe. The structure mirrors
 * MarkdownPreview.tsx exactly: .slide > .slide__container > .slide__layout.
 */
export function buildPreviewDocument(options: {
  themeName: string;
  layoutClass: string;
  themeCss: string;
  slideInner: string;
  isLight: boolean;
  /** Preview-only CSS (e.g. placeholder side images) the theme can override. */
  previewCss?: string;
  /**
   * `--vscode-*` custom properties forwarded from the host so the theme's
   * `var(--vscode-…)` references resolve. The sandboxed iframe doesn't inherit
   * them. Empty in the standalone app, where the references' fallbacks apply.
   */
  rootVars?: string;
}): string {
  const {
    themeName,
    layoutClass,
    themeCss,
    slideInner,
    isLight,
    previewCss = '',
    rootVars = '',
  } = options;
  const lightClass = isLight ? ' light' : '';
  const escapeStyleText = (css: string) => css.replace(/<\/style/gi, '<\\/style');
  const safePreviewCss = escapeStyleText(previewCss);
  const safeThemeCss = escapeStyleText(themeCss);

  return `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <style>${PREVIEW_BASE_CSS}</style>
    <style>${ENVIRONMENT_CSS}</style>
    <style id="vscode-vars">:root{${rootVars}}</style>
    <style>${safePreviewCss}</style>
    <style id="theme">${safeThemeCss}</style>
    <style>
      html, body { margin: 0; padding: 0; background: #000; }
    </style>
  </head>
  <body>
    <div class="slide ${themeName}${lightClass}">
      <div class="slide__container">
        <div class="slide__layout ${layoutClass}">
          ${slideInner}
        </div>
      </div>
    </div>
  </body>
</html>`;
}
