import { ThemeConfig } from '../types/theme';

export const generateThemeCSS = (theme: ThemeConfig): string => {
  const { name, layouts } = theme;
  
  return `@import 'tailwindcss';

/* ${name} Theme - Generated by Demo Time Theme Builder */
.slide.${name} {
  /* Global colors */
  --demotime-color: ${theme.color};
  --demotime-background: ${theme.background};
  
  --demotime-heading-color: ${theme.headingColor};
  --demotime-heading-background: ${theme.headingBackground};
  
  --demotime-font-size: ${theme.fontSize};
  
  --demotime-link-color: ${theme.linkColor};
  --demotime-link-active-color: ${theme.linkActiveColor};
  
  --demotime-blockquote-border: ${theme.blockquoteBorder};
  --demotime-blockquote-background: ${theme.blockquoteBackground};
  
  /* Default layout */
  --demotime-default-background: ${layouts.default.background};
  --demotime-default-color: ${layouts.default.color};
  --demotime-default-heading-color: ${layouts.default.headingColor};
  --demotime-default-heading-background: ${layouts.default.headingBackground};
  
  /* Intro layout */
  --demotime-intro-background: ${layouts.intro.background};
  --demotime-intro-color: ${layouts.intro.color};
  --demotime-intro-heading-color: ${layouts.intro.headingColor};
  --demotime-intro-heading-background: ${layouts.intro.headingBackground};
  
  /* Quote layout */
  --demotime-quote-background: ${layouts.quote.background};
  --demotime-quote-color: ${layouts.quote.color};
  --demotime-quote-heading-color: ${layouts.quote.headingColor};
  --demotime-quote-heading-background: ${layouts.quote.headingBackground};
  
  /* Section layout */
  --demotime-section-background: ${layouts.section.background};
  --demotime-section-color: ${layouts.section.color};
  --demotime-section-heading-color: ${layouts.section.headingColor};
  --demotime-section-heading-background: ${layouts.section.headingBackground};
  
  /* Image Left layout */
  --demotime-image-left-background: ${layouts.imageLeft.background};
  --demotime-image-left-color: ${layouts.imageLeft.color};
  --demotime-image-left-heading-color: ${layouts.imageLeft.headingColor};
  --demotime-image-left-heading-background: ${layouts.imageLeft.headingBackground};
  
  /* Image Right layout */
  --demotime-image-right-background: ${layouts.imageRight.background};
  --demotime-image-right-color: ${layouts.imageRight.color};
  --demotime-image-right-heading-color: ${layouts.imageRight.headingColor};
  --demotime-image-right-heading-background: ${layouts.imageRight.headingBackground};
  
  /* Two Columns layout */
  --demotime-two-columns-background: ${layouts.twoColumns.background};
  --demotime-two-columns-color: ${layouts.twoColumns.color};
  --demotime-two-columns-heading-color: ${layouts.twoColumns.headingColor};
  --demotime-two-columns-heading-background: ${layouts.twoColumns.headingBackground};
  
  background: var(--demotime-background);
  color: var(--demotime-color);
  font-size: var(--demotime-font-size);
  
  .slide__content__inner {
    padding: 2rem;
    box-sizing: border-box;
  }
  
  h1 {
    font-size: 2.5rem;
    color: var(--demotime-heading-color);
    background: var(--demotime-heading-background);
  }
  
  h2 {
    font-size: 2rem;
    color: var(--demotime-heading-color);
    background: var(--demotime-heading-background);
  }
  
  h3 {
    font-size: 1.75rem;
    color: var(--demotime-heading-color);
    background: var(--demotime-heading-background);
  }
  
  h4 {
    font-size: 1.5rem;
    color: var(--demotime-heading-color);
    background: var(--demotime-heading-background);
  }
  
  h5 {
    font-size: 1.25rem;
    color: var(--demotime-heading-color);
    background: var(--demotime-heading-background);
  }
  
  p {
    line-height: 1.6;
  }
  
  a {
    color: var(--demotime-link-color);
    text-decoration: underline;
    
    &:hover {
      color: var(--demotime-link-active-color);
    }
  }
  
  ul, ol {
    margin-left: 1.5rem;
    
    li {
      margin-bottom: 0.5rem;
    }
    
    ul, ol {
      margin-top: 0.5rem;
    }
  }
  
  ul {
    list-style: disc;
  }
  
  ol {
    list-style: decimal;
  }
  
  blockquote {
    border-left: 4px solid var(--demotime-blockquote-border);
    padding: 1rem;
    background: var(--demotime-blockquote-background);
  }
  
  /* Layout-specific styles */
  .default {
    background: var(--demotime-default-background);
    color: var(--demotime-default-color);
    
    h1 {
      color: var(--demotime-default-heading-color);
      background: var(--demotime-default-heading-background);
    }
  }
  
  .intro {
    background: var(--demotime-intro-background);
    color: var(--demotime-intro-color);
    
    .slide__content__inner {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      text-align: center;
      height: 100%;
    }
    
    h1 {
      font-size: 3.5rem;
      color: var(--demotime-intro-heading-color);
      background: var(--demotime-intro-heading-background);
    }
  }
  
  .quote {
    background: var(--demotime-quote-background);
    color: var(--demotime-quote-color);
    
    .slide__content__inner {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      text-align: center;
      height: 100%;
    }
    
    h1 {
      font-size: 2.5rem;
      color: var(--demotime-quote-heading-color);
      background: var(--demotime-quote-heading-background);
      font-style: italic;
    }
  }
  
  .section {
    background: var(--demotime-section-background);
    color: var(--demotime-section-color);
    
    .slide__content__inner {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      text-align: center;
      height: 100%;
    }
    
    h1 {
      font-size: 3.5rem;
      color: var(--demotime-section-heading-color);
      background: var(--demotime-section-heading-background);
    }
  }
  
  .image {
    .slide__content__inner {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      text-align: center;
    }
  }
  
  .video {
    .slide__content__inner {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      text-align: center;
      background-color: transparent;
    }
  }
  
  .image-left {
    background: var(--demotime-image-left-background);
    color: var(--demotime-image-left-color);
    
    h1 {
      color: var(--demotime-image-left-heading-color);
      background: var(--demotime-image-left-heading-background);
    }
  }
  
  .image-right {
    background: var(--demotime-image-right-background);
    color: var(--demotime-image-right-color);
    
    h1 {
      color: var(--demotime-image-right-heading-color);
      background: var(--demotime-image-right-heading-background);
    }
  }
  
  .two-columns {
    background: var(--demotime-two-columns-background);
    color: var(--demotime-two-columns-color);
    
    .slide__content__inner {
      width: 100%;
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 2rem;
    }
    
    .slide__left,
    .slide__right {
      width: 100%;
    }
    
    h1 {
      color: var(--demotime-two-columns-heading-color);
      background: var(--demotime-two-columns-heading-background);
    }
  }
}
`;
};

export const downloadTheme = (theme: ThemeConfig): void => {
  const css = generateThemeCSS(theme);
  const blob = new Blob([css], { type: 'text/css' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${theme.name}.css`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};
