export enum Action {
  // File
  Create = 'create',
  Open = 'open',
  Rename = 'rename',
  DeleteFile = 'deleteFile',
  Close = 'close',
  CloseAll = 'closeAll',
  Copy = 'copy',
  Move = 'move',
  // Previews
  MarkdownPreview = 'markdownPreview',
  ImagePreview = 'imagePreview',
  OpenSlide = 'openSlide',
  // Code
  Insert = 'insert',
  Highlight = 'highlight',
  Replace = 'replace',
  Unselect = 'unselect',
  Delete = 'delete',
  PositionCursor = 'positionCursor',
  Write = 'write',
  Save = 'save',
  Format = 'format',
  ApplyPatch = 'applyPatch',
  // Settings
  SetSetting = 'setSetting',
  SetTheme = 'setTheme',
  UnsetTheme = 'unsetTheme',
  SetPresentationView = 'setPresentationView',
  UnsetPresentationView = 'unsetPresentationView',
  BackupSettings = 'backupSettings',
  RestoreSettings = 'restoreSettings',
  // Timeout
  WaitForTimeout = 'waitForTimeout',
  WaitForInput = 'waitForInput',
  Pause = 'pause',
  // VSCode
  ExecuteVSCodeCommand = 'executeVSCodeCommand',
  ShowInfoMessage = 'showInfoMessage',
  SetState = 'setState',
  OpenWebsite = 'openWebsite',
  // Terminal
  OpenTerminal = 'openTerminal',
  ExecuteTerminalCommand = 'executeTerminalCommand',
  CloseTerminal = 'closeTerminal',
  ExecuteScript = 'executeScript',
  // Extensibility
  Snippet = 'snippet',
  // External applications
  OpenPowerPoint = 'openPowerPoint',
  OpenKeynote = 'openKeynote',
  // GitHub Copilot
  OpenChat = 'openCopilotChat',
  NewChat = 'newCopilotChat',
  AskChat = 'askCopilotChat',
  EditChat = 'editCopilotChat',
  AgentChat = 'agentCopilotChat',
  CustomChat = 'customCopilotChat',
  CloseChat = 'closeCopilotChat',
  // Interaction
  TypeText = 'typeText',
  CopyToClipboard = 'copyToClipboard',
  PasteFromClipboard = 'pasteFromClipboard',
  PressEnter = 'pressEnter',
  PressTab = 'pressTab',
  PressArrowLeft = 'pressArrowLeft',
  PressArrowRight = 'pressArrowRight',
  PressArrowUp = 'pressArrowUp',
  PressArrowDown = 'pressArrowDown',
  PressEscape = 'pressEscape',
  PressBackspace = 'pressBackspace',
  PressDelete = 'pressDelete',
  // Demo Time
  RunDemoById = 'runDemoById',
  // EngageTime
  StartEngageTimeSession = 'startEngageTimeSession',
  StartEngageTimePoll = 'startEngageTimePoll',
  CloseEngageTimeSession = 'closeEngageTimeSession',
  CloseEngageTimePoll = 'closeEngageTimePoll',
  ShowEngageTimeSession = 'showEngageTimeSession',
  ShowEngageTimePoll = 'showEngageTimePoll',
  SendEngageTimeMessage = 'sendEngageTimeMessage',
}
