#!/usr/bin/env node
/**
 * Generates the reference files and helper scripts of the Demo Time AI skills in `skills/`.
 *
 * - `references/*.md` are converted from the documentation in `docs/src/content/docs`, so the
 *   skills stay in sync when actions, layouts or themes change.
 * - `demotime-code-demo/references/demo-time.schema.json` is a copy of the act file JSON schema.
 * - `demotime-slides/references/slide.schema.json` is a copy of the slide front matter JSON schema.
 * - `demotime-slide-theme/references/theme-model.md` and `built-in-css/*.css` come from the Theme
 *   Builder source.
 * - `scripts/*.mjs` are bundled from `scripts/skills/*.ts`.
 *
 * The `references` and `scripts` folders of every skill are generated and not in source control.
 * The extension build runs this script, and the release workflow packs the result with
 * `pack-skills.mjs` for the Claude Code plugin.
 *
 * Usage: node scripts/skills/build-skills.mjs
 */
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, posix, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..', '..');
const DOCS = join(ROOT, 'docs', 'src', 'content', 'docs');
const SKILLS = join(ROOT, 'skills');
const SITE = 'https://demotime.show';
const REPO = 'https://github.com/estruyf/vscode-demo-time/blob/main';

const GENERATED_NOTE = (source) =>
  `<!-- Generated by scripts/skills/build-skills.mjs from ${source}. Do not edit this file. -->`;

const LAYOUT_PAGES = [
  'slides/layouts/index.mdx',
  'slides/layouts/default.mdx',
  'slides/layouts/center.mdx',
  'slides/layouts/intro.mdx',
  'slides/layouts/section.mdx',
  'slides/layouts/quote.mdx',
  'slides/layouts/image.mdx',
  'slides/layouts/image-left.mdx',
  'slides/layouts/image-right.mdx',
  'slides/layouts/two-columns.mdx',
  'slides/layouts/video.mdx',
  'slides/layouts/animated.mdx',
];

const THEME_PAGES = [
  'slides/themes/index.mdx',
  'slides/themes/default.mdx',
  'slides/themes/minimal.mdx',
  'slides/themes/monomi.mdx',
  'slides/themes/unnamed.mdx',
  'slides/themes/quantum.mdx',
  'slides/themes/frost.mdx',
  'slides/themes/pixels.mdx',
];

/** Reference files per skill: output file -> documentation pages (relative to DOCS). */
const DOC_REFERENCES = {
  'demotime-talk-plan': {
    'terminology.md': ['references/terminology.mdx'],
    'presenting.md': [
      'presentation-mode.mdx',
      'features/presenter-view.mdx',
      'features/using-notes.mdx',
      'features/timer-clock.mdx',
    ],
  },
  'demotime-slides': {
    'slides.md': ['slides/index.mdx'],
    'front-matter.md': ['slides/front-matter.mdx'],
    'layouts.md': LAYOUT_PAGES,
    'custom-layouts.md': ['slides/layouts/custom.mdx', 'slides/layouts/header-footer.mdx'],
    'components.md': ['slides/components/index.mdx', 'slides/components/custom.mdx'],
    'animations.md': ['slides/animations.mdx', 'slides/transitions.mdx'],
    'mermaid.md': ['slides/mermaid.mdx'],
    'themes.md': ['slides/themes/index.mdx'],
    'notes.md': ['features/using-notes.mdx'],
    'moves.md': ['adding-moves.mdx', 'actions/preview.mdx'],
  },
  'demotime-slide-theme': {
    'custom-theme.md': ['slides/themes/custom.mdx', 'slides/themes/theme-builder.mdx'],
    'built-in-themes.md': THEME_PAGES,
    'layouts.md': LAYOUT_PAGES,
    'custom-layouts.md': ['slides/layouts/custom.mdx', 'slides/layouts/header-footer.mdx'],
    'components.md': ['slides/components/index.mdx', 'slides/components/custom.mdx'],
  },
  'demotime-code-demo': {
    'act-files.md': [
      'references/terminology.mdx',
      'adding-moves.mdx',
      'references/json-schema.mdx',
    ],
    'highlighting.md': ['tips/highlighting.mdx'],
    'variables.md': ['tips/variables.mdx'],
    'notes.md': ['features/using-notes.mdx'],
    'snippets.md': ['snippets/index.mdx'],
    'tips.md': ['tips/adding-content.mdx', 'tips/adding-steps.mdx', 'tips/control-next-demo.mdx'],
    ...Object.fromEntries(
      readdirSync(join(DOCS, 'actions'))
        .filter((file) => file.endsWith('.mdx'))
        .sort()
        .map((file) => [`actions/${file.replace(/\.mdx$/, '.md')}`, [`actions/${file}`]]),
    ),
  },
};

/* ------------------------------------------------------------------ MDX -> Markdown */

const HTML_TAGS = 'div|span|p|svg|path|h[1-6]|ul|li|br|section|article|figure|figcaption|img';

function slugOf(page) {
  const slug = page.replace(/\.mdx?$/, '').replace(/(^|\/)index$/, '');
  return slug ? `/${slug}/` : '/';
}

function absoluteUrl(url, pageSlug) {
  if (/^(https?:|mailto:|#)/.test(url)) {
    return url;
  }
  if (url.startsWith('/')) {
    return `${SITE}${url}`;
  }
  return `${SITE}${posix.join(pageSlug, url)}`;
}

function parseAttrs(source) {
  const attrs = {};
  const re = /([\w-]+)=(?:"([^"]*)"|'([^']*)'|\{`([\s\S]*?)`\}|\{"([^"]*)"\}|\{([^}]*)\})/g;
  let match;
  while ((match = re.exec(source))) {
    attrs[match[1]] = match[2] ?? match[3] ?? match[4] ?? match[5] ?? match[6];
  }
  return attrs;
}

/** Read a (possibly multi-line) JSX tag that starts at lines[idx]. Returns the tag and next index. */
function readTag(lines, idx, endPattern = /\/?>\s*$/) {
  let tag = lines[idx];
  let i = idx;
  while (!endPattern.test(tag) && i < lines.length - 1) {
    i++;
    tag += `\n${lines[i]}`;
  }
  return { tag, next: i + 1 };
}

function cleanInline(line, pageSlug) {
  return line
    .replace(/\{\/\*[\s\S]*?\*\/\}/g, '')
    .replace(/<svg[\s\S]*?<\/svg>/g, '')
    .replace(/<code>([\s\S]*?)<\/code>/g, '`$1`')
    .replace(/<(?:b|strong)>([\s\S]*?)<\/(?:b|strong)>/g, '**$1**')
    .replace(/<h[1-6][^>]*>([\s\S]*?)<\/h[1-6]>/g, '**$1**')
    .replace(/<a\s+href="([^"]+)"[^>]*>([\s\S]*?)<\/a>/g, (_, href, text) => {
      return `[${text}](${absoluteUrl(href, pageSlug)})`;
    })
    .replace(new RegExp(`</?(?:${HTML_TAGS})\\b[^>]*>`, 'g'), '')
    .replace(/\]\(([^)\s]+)\)/g, (_, url) => `](${absoluteUrl(url, pageSlug)})`);
}

export function mdxToMarkdown(source, page) {
  const pageSlug = slugOf(page);
  const fmMatch = source.match(/^---\n([\s\S]*?)\n---\n?/);
  const frontmatter = fmMatch ? fmMatch[1] : '';
  const field = (name) => {
    const match = frontmatter.match(new RegExp(`^${name}:\\s*(.*)$`, 'm'));
    return match ? match[1].trim().replace(/^["']|["']$/g, '') : '';
  };
  const title = field('title') || page;
  const description = field('description');

  const lines = (fmMatch ? source.slice(fmMatch[0].length) : source).split('\n');
  const out = [];
  let fence = null;
  let asideDepth = 0;

  const push = (line) => out.push(asideDepth > 0 ? (line ? `> ${line}` : '>') : line);

  for (let i = 0; i < lines.length; ) {
    const line = lines[i];
    const trimmed = line.trim();

    // Code fences are copied as they are.
    const fenceMatch = trimmed.match(/^(`{3,}|~{3,})/);
    if (fence) {
      push(line);
      if (fenceMatch && trimmed.startsWith(fence) && trimmed.replace(/[`~]/g, '') === '') {
        fence = null;
      }
      i++;
      continue;
    }
    if (fenceMatch) {
      fence = fenceMatch[1];
      push(line);
      i++;
      continue;
    }

    // Imports
    if (/^import\s/.test(trimmed)) {
      let j = i;
      while (
        j < lines.length &&
        !/from\s+['"][^'"]+['"];?\s*$|^import\s+['"]/.test(lines[j].trim())
      ) {
        j++;
      }
      i = j + 1;
      continue;
    }

    // MDX comments
    if (trimmed.startsWith('{/*')) {
      const { next } = readTag(lines, i, /\*\/\}\s*$/);
      i = next;
      continue;
    }

    // Tabs: keep the label of every tab so both the JSON and YAML variants stay readable.
    if (/^<\/?Tabs\b/.test(trimmed) || trimmed === '</TabItem>') {
      i++;
      continue;
    }
    const tabItem = trimmed.match(/^<TabItem\b([^>]*)>$/);
    if (tabItem) {
      const label = parseAttrs(tabItem[1]).label;
      if (label) {
        push(`**${label}**`);
        push('');
      }
      i++;
      continue;
    }

    // Asides become block quotes.
    const aside = trimmed.match(/^<Aside\b([^>]*)>(.*)$/);
    if (aside) {
      const attrs = parseAttrs(aside[1]);
      const kind = (attrs.type || 'note').replace(/^\w/, (c) => c.toUpperCase());
      push('');
      asideDepth++;
      push(`**${kind}${attrs.title ? `: ${attrs.title}` : ''}**`);
      push('');
      let rest = aside[2];
      const closesInline = rest.includes('</Aside>');
      rest = rest.replace('</Aside>', '').trim();
      if (rest) {
        push(cleanInline(rest, pageSlug));
      }
      if (closesInline) {
        asideDepth--;
        push('');
      }
      i++;
      continue;
    }
    if (trimmed.includes('</Aside>')) {
      const before = trimmed.replace('</Aside>', '').trim();
      if (before) {
        push(cleanInline(before, pageSlug));
      }
      asideDepth = Math.max(0, asideDepth - 1);
      push('');
      i++;
      continue;
    }

    // <Code code={`...`} lang="json" title="..." />
    if (/^<Code\b/.test(trimmed)) {
      const { tag, next } = readTag(lines, i, /\/>\s*$/);
      const attrs = parseAttrs(tag);
      push(`\`\`\`${attrs.lang ?? ''}${attrs.title ? ` title="${attrs.title}"` : ''}`);
      for (const codeLine of (attrs.code ?? '').split('\n')) {
        push(codeLine);
      }
      push('```');
      i = next;
      continue;
    }

    // <GitHubFileOpener filePath="..." /> becomes a link to the file on GitHub.
    if (/^<GitHubFileOpener\b/.test(trimmed)) {
      const { tag, next } = readTag(lines, i, /\/>\s*$/);
      const filePath = parseAttrs(tag).filePath;
      if (filePath) {
        push(`[${filePath}](${REPO}/${filePath})`);
      }
      i = next;
      continue;
    }

    // Media and site-only components are left out.
    if (/^<(Image|LinkButton|LinkCard|CardGrid|Card|CustomCard|YouTubeEmbed)\b/.test(trimmed)) {
      const selfClosing = /^<(Image|LinkCard|YouTubeEmbed)\b/.test(trimmed);
      const name = trimmed.match(/^<(\w+)/)[1];
      const end = selfClosing ? /\/>\s*$/ : new RegExp(`</${name}>\\s*$|/>\\s*$`);
      const { next } = readTag(lines, i, end);
      i = next;
      continue;
    }
    if (/^<\/(CardGrid|Card|CustomCard)>/.test(trimmed)) {
      i++;
      continue;
    }
    if (/^<(video|iframe)\b/.test(trimmed)) {
      const name = trimmed.match(/^<(\w+)/)[1];
      const { next } = readTag(lines, i, new RegExp(`</${name}>\\s*$`));
      i = next;
      continue;
    }

    const cleaned = cleanInline(line, pageSlug);
    // Lines that only held layout HTML are dropped instead of leaving whitespace behind.
    if (cleaned.trim() === '' && trimmed !== '') {
      i++;
      continue;
    }
    // Keep the indentation of nested list items only, indented HTML would become a code block.
    const isListItem = /^\s*([-*+]|\d+\.)\s/.test(cleaned);
    push(isListItem && asideDepth === 0 ? cleaned.trimEnd() : cleaned.trim());
    i++;
  }

  const body = out
    .join('\n')
    .replace(/\n(>\n)+(?=\n|$)/g, '\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();

  return [
    `# ${title}`,
    '',
    ...(description ? [`> ${description}`, ''] : []),
    `Source: ${SITE}${pageSlug}`,
    '',
    body,
  ].join('\n');
}

/* ------------------------------------------------------------------ generation */

/** All generated files: path relative to SKILLS -> content. */
function collectGeneratedFiles() {
  const files = new Map();

  for (const [skill, references] of Object.entries(DOC_REFERENCES)) {
    for (const [file, pages] of Object.entries(references)) {
      const sources = pages.map((page) => `docs/src/content/docs/${page}`).join(', ');
      const content = pages
        .map((page) => mdxToMarkdown(readFileSync(join(DOCS, page), 'utf8'), page))
        .join('\n\n---\n\n');
      files.set(`${skill}/references/${file}`, `${GENERATED_NOTE(sources)}\n\n${content}\n`);
    }
  }

  // Act file JSON schema
  files.set(
    'demotime-code-demo/references/demo-time.schema.json',
    readFileSync(join(ROOT, 'docs', 'public', 'demo-time.schema.json'), 'utf8'),
  );

  // Slide front matter JSON schema
  files.set(
    'demotime-slides/references/slide.schema.json',
    readFileSync(join(ROOT, 'docs', 'public', 'slide.schema.json'), 'utf8'),
  );

  // Theme model, from the Theme Builder types
  const themeTypes = readFileSync(join(ROOT, 'apps/webviews/src/types/theme.ts'), 'utf8');
  files.set(
    'demotime-slide-theme/references/theme-model.md',
    [
      GENERATED_NOTE('apps/webviews/src/types/theme.ts'),
      '',
      '# Theme model',
      '',
      'The Theme Builder stores a theme as a `ThemeModel` JSON object. `scripts/build-theme.mjs` turns a',
      'model into the theme CSS, the same way the Theme Builder exports it. A partial model is fine:',
      'missing properties get the Theme Builder defaults.',
      '',
      '- Colours are any CSS colour value, or a `var(--vscode-…, fallback)` reference to follow the',
      '  active VS Code theme.',
      '- Font and heading sizes are in `em`/`rem` as described in the comments; `baseFontSize` is in px.',
      '- Per-layout `colors` left empty and `typography` values left `0` inherit the global value.',
      '- `basedOn` builds on a built-in design (`default`, `minimal`, `monomi`, `unnamed`, `quantum`,',
      '  `frost`, `pixels`). Its CSS is in `built-in-css/`. Leave it out for a theme from scratch.',
      '- `customCss` is appended after the generated rules. Scope every rule to `.slide.<name>`.',
      '',
      '```ts',
      themeTypes.trim(),
      '```',
      '',
    ].join('\n'),
  );

  // Built-in theme designs, compiled to plain CSS
  const presetSource = readFileSync(
    join(ROOT, 'apps/webviews/src/utils/theme-builder/presetCss.generated.ts'),
    'utf8',
  );
  const presetJson = presetSource.slice(
    presetSource.indexOf('{'),
    presetSource.lastIndexOf('}') + 1,
  );
  for (const [name, css] of Object.entries(JSON.parse(presetJson))) {
    files.set(
      `demotime-slide-theme/references/built-in-css/${name}.css`,
      `/* Generated by scripts/skills/build-skills.mjs from the built-in "${name}" theme. Do not edit this file. */\n${css.trim()}\n`,
    );
  }

  return files;
}

async function bundleScripts() {
  const { build } = await import('esbuild');
  const bundles = [
    { entry: 'theme-cli.ts', out: 'demotime-slide-theme/scripts/build-theme.mjs' },
    { entry: 'validate-act.ts', out: 'demotime-code-demo/scripts/validate-act.mjs' },
  ];

  for (const { entry, out } of bundles) {
    await build({
      entryPoints: [join(__dirname, entry)],
      outfile: join(SKILLS, out),
      bundle: true,
      platform: 'node',
      mainFields: ['module', 'main'],
      format: 'esm',
      target: 'node18',
      minify: true,
      legalComments: 'none',
      logLevel: 'warning',
      banner: {
        js: [
          '#!/usr/bin/env node',
          `// Generated by scripts/skills/build-skills.mjs from scripts/skills/${entry}. Do not edit this file.`,
          "import { createRequire as __createRequire } from 'node:module';",
          'const require = __createRequire(import.meta.url);',
        ].join('\n'),
      },
    });
  }
}

/** The folders of every skill that this script owns: they are emptied before generating. */
const GENERATED_FOLDERS = ['references', 'scripts'];

async function main() {
  const files = collectGeneratedFiles();

  for (const skill of readdirSync(SKILLS, { withFileTypes: true })) {
    if (skill.isDirectory()) {
      for (const folder of GENERATED_FOLDERS) {
        rmSync(join(SKILLS, skill.name, folder), { recursive: true, force: true });
      }
    }
  }

  for (const [file, content] of files) {
    const target = join(SKILLS, file);
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, content, 'utf8');
  }
  await bundleScripts();

  console.log(
    `Generated ${files.size} reference files and 2 scripts in ${relative(ROOT, SKILLS)}/`,
  );
}

await main();
