/*
 * Compile the real built-in Demo Time themes (which use @apply + Tailwind) into
 * standalone plain CSS the theme-builder can preview and export directly.
 *
 * Source of truth: apps/vscode-extension/assets/styles/themes/*.css
 * Output:          apps/theme-builder/src/lib/presetCss.generated.ts
 *
 * Run from repo root:  node apps/theme-builder/scripts/compile-themes.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import postcss from 'postcss';
import tailwind from '@tailwindcss/postcss';

const here = dirname(fileURLToPath(import.meta.url));
const themesDir = resolve(here, '../../vscode-extension/assets/styles/themes');
const outFile = resolve(here, '../src/lib/presetCss.generated.ts');
const previewCssFile = resolve(here, '../../webviews/src/styles/preview.css');
const previewOutFile = resolve(here, '../src/lib/previewBase.generated.ts');

const THEMES = ['default', 'minimal', 'monomi', 'unnamed', 'quantum', 'frost', 'pixels'];

/**
 * Concrete fallbacks for the VS Code editor variables the dark-ish themes lean
 * on, so they render correctly outside of VS Code (Dark+ palette).
 */
const VSCODE_FALLBACKS = {
  'editor-foreground': '#d4d4d4',
  'editor-background': '#1e1e1e',
  'editor-font-size': '24px',
  'textLink-foreground': '#4daafc',
  'textLink-activeForeground': '#9cdcfe',
  'textBlockQuote-border': '#4daafc',
  'textBlockQuote-background': 'rgba(255,255,255,0.04)',
  'textPreformat-foreground': '#ce9178',
  'textPreformat-background': 'rgba(255,255,255,0.08)',
  'panel-border': '#3a3a3a',
  'panel-background': '#1e1e1e',
  'activityBarBadge-foreground': '#ffffff',
  'activityBarBadge-background': '#007acc',
  'widget-shadow': 'rgba(0,0,0,0.36)',
  'keybindingTable-headerBackground': 'rgba(255,255,255,0.04)',
};

/**
 * Find the index just past the `)` that closes the `var(` starting at `open`,
 * accounting for nested parens.
 */
function matchingParen(css, open) {
  let depth = 0;
  for (let i = open; i < css.length; i++) {
    if (css[i] === '(') {
      depth++;
    } else if (css[i] === ')') {
      depth--;
      if (depth === 0) {
        return i + 1;
      }
    }
  }
  return css.length;
}

/**
 * Keep every `var(--vscode-*)` reference intact so the theme follows the active
 * VS Code editor theme, but guarantee each one carries a concrete fallback so it
 * still renders in the standalone builder (and wherever the variable is absent).
 * The theme-builder preview forwards the real `--vscode-*` values into its
 * iframe, so the references resolve live there. Recurses through nested `var()`
 * fallbacks (e.g. `var(--vscode-panel-background, var(--vscode-editor-background))`).
 */
function ensureVscodeFallbacks(css) {
  let out = '';
  let i = 0;
  while (i < css.length) {
    const open = css.indexOf('var(', i);
    if (open === -1) {
      out += css.slice(i);
      break;
    }
    out += css.slice(i, open);
    const close = matchingParen(css, open + 3);
    out += rewriteVar(css.slice(open, close));
    i = close;
  }
  return out;
}

/** Rewrite a single, balanced `var(...)` expression, ensuring vscode fallbacks. */
function rewriteVar(expr) {
  const inner = expr.slice(4, -1).trim(); // strip `var(` and the trailing `)`
  const comma = inner.indexOf(',');
  const name = (comma === -1 ? inner : inner.slice(0, comma)).trim();
  // Process the fallback first — it can itself contain nested var() references.
  let fallback = comma === -1 ? '' : ensureVscodeFallbacks(inner.slice(comma + 1).trim());

  if (name.startsWith('--vscode-') && !fallback) {
    fallback = VSCODE_FALLBACKS[name.slice('--vscode-'.length)] ?? '';
  }

  return fallback ? `var(${name}, ${fallback})` : `var(${name})`;
}

const compiled = {};

for (const name of THEMES) {
  const src = readFileSync(resolve(themesDir, `${name}.css`), 'utf8');
  // Drop the theme's own tailwind import; use @reference so utilities are
  // available to @apply without emitting preflight or the utility layer.
  const body = src.replace(/@import\s+['"]tailwindcss['"];?/g, '');
  const input = `@reference "tailwindcss";\n${body}`;

  const result = await postcss([tailwind()]).process(input, { from: resolve(themesDir, `${name}.css`) });
  let out = result.css;

  // Drop the Tailwind banner comment and ensure VS Code variables keep a
  // fallback (without flattening the reference, so themes stay theme-aware).
  out = ensureVscodeFallbacks(out)
    .replace(/\/\*!\s*tailwindcss[\s\S]*?\*\/\s*/i, '')
    .trim();

  compiled[name] = out;
  const hasApply = /@apply/.test(out);
  console.log(`${name}: ${out.length} chars${hasApply ? '  ⚠ STILL HAS @apply' : ''}`);
}

const header = `/* AUTO-GENERATED by scripts/compile-themes.mjs — do not edit by hand.
 * Standalone, plain-CSS builds of the real built-in Demo Time themes
 * (source: apps/vscode-extension/assets/styles/themes). */
/* eslint-disable */
export const PRESET_CSS: Record<string, string> = ${JSON.stringify(compiled, null, 2)};
`;

writeFileSync(outFile, header, 'utf8');
console.log(`\nWrote ${outFile}`);

/* ----------------------------------------------------------------------- */
/* The slide environment: the REAL preview.css the extension webview uses,
 * compiled with the REAL Tailwind preflight + theme variables. The builder's
 * preview iframe loads this so both previews share the exact same base CSS
 * and can never drift apart. */

const previewSrc = readFileSync(previewCssFile, 'utf8');
const previewBody = previewSrc.replace(/@import\s+['"]tailwindcss['"];?/g, '');
const previewInput = [
  '@layer theme, base, components, utilities;',
  '@import "tailwindcss/theme.css" layer(theme);',
  '@import "tailwindcss/preflight.css" layer(base);',
  '@reference "tailwindcss";',
  previewBody,
].join('\n');

const previewResult = await postcss([tailwind()]).process(previewInput, { from: previewCssFile });
const previewOut = ensureVscodeFallbacks(previewResult.css)
  .replace(/\/\*!\s*tailwindcss[\s\S]*?\*\/\s*/i, '')
  .trim();

if (/@apply/.test(previewOut)) {
  console.warn('preview base: ⚠ STILL HAS @apply');
}

const previewHeader = `/* AUTO-GENERATED by scripts/compile-themes.mjs — do not edit by hand.
 * The real slide environment: Tailwind preflight + theme variables + the
 * compiled apps/webviews/src/styles/preview.css the extension webview ships.
 * Loading this in the preview iframe keeps the builder's rendering identical
 * to the real slide preview. */
/* eslint-disable */
export const PREVIEW_BASE_CSS: string = ${JSON.stringify(previewOut)};
`;

writeFileSync(previewOutFile, previewHeader, 'utf8');
console.log(`Wrote ${previewOutFile} (${previewOut.length} chars)`);
