/*
 * Compile the real built-in Demo Time themes (which use @apply + Tailwind) into
 * standalone plain CSS the theme-builder can preview and export directly.
 *
 * Source of truth: apps/vscode-extension/assets/styles/themes/*.css
 * Output:          apps/theme-builder/src/lib/presetCss.generated.ts
 *
 * Run from repo root:  node apps/theme-builder/scripts/compile-themes.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import postcss from 'postcss';
import tailwind from '@tailwindcss/postcss';

const here = dirname(fileURLToPath(import.meta.url));
const themesDir = resolve(here, '../../vscode-extension/assets/styles/themes');
const outFile = resolve(here, '../src/lib/presetCss.generated.ts');

const THEMES = ['default', 'minimal', 'monomi', 'unnamed', 'quantum', 'frost', 'pixels'];

/**
 * Concrete fallbacks for the VS Code editor variables the dark-ish themes lean
 * on, so they render correctly outside of VS Code (Dark+ palette).
 */
const VSCODE_FALLBACKS = {
  'editor-foreground': '#d4d4d4',
  'editor-background': '#1e1e1e',
  'editor-font-size': '24px',
  'textLink-foreground': '#4daafc',
  'textLink-activeForeground': '#9cdcfe',
  'textBlockQuote-border': '#4daafc',
  'textBlockQuote-background': 'rgba(255,255,255,0.04)',
  'textPreformat-foreground': '#ce9178',
  'textPreformat-background': 'rgba(255,255,255,0.08)',
  'panel-border': '#3a3a3a',
  'panel-background': '#1e1e1e',
  'activityBarBadge-foreground': '#ffffff',
  'activityBarBadge-background': '#007acc',
  'widget-shadow': 'rgba(0,0,0,0.36)',
  'keybindingTable-headerBackground': 'rgba(255,255,255,0.04)',
};

/** Replace remaining `var(--vscode-x, fallback?)` with a concrete value. */
function resolveVscodeVars(css) {
  return css.replace(/var\(\s*--vscode-([a-zA-Z0-9-]+)\s*(?:,\s*([^)]+))?\)/g, (_m, name, fallback) => {
    if (VSCODE_FALLBACKS[name] !== undefined) {
      return VSCODE_FALLBACKS[name];
    }
    return (fallback ?? '').trim() || 'inherit';
  });
}

const compiled = {};

for (const name of THEMES) {
  const src = readFileSync(resolve(themesDir, `${name}.css`), 'utf8');
  // Drop the theme's own tailwind import; use @reference so utilities are
  // available to @apply without emitting preflight or the utility layer.
  const body = src.replace(/@import\s+['"]tailwindcss['"];?/g, '');
  const input = `@reference "tailwindcss";\n${body}`;

  const result = await postcss([tailwind()]).process(input, { from: resolve(themesDir, `${name}.css`) });
  let out = result.css;

  // Drop the Tailwind banner comment and resolve VS Code variables.
  out = resolveVscodeVars(out)
    .replace(/\/\*!\s*tailwindcss[\s\S]*?\*\/\s*/i, '')
    .trim();

  compiled[name] = out;
  const hasApply = /@apply/.test(out);
  console.log(`${name}: ${out.length} chars${hasApply ? '  ⚠ STILL HAS @apply' : ''}`);
}

const header = `/* AUTO-GENERATED by scripts/compile-themes.mjs — do not edit by hand.
 * Standalone, plain-CSS builds of the real built-in Demo Time themes
 * (source: apps/vscode-extension/assets/styles/themes). */
/* eslint-disable */
export const PRESET_CSS: Record<string, string> = ${JSON.stringify(compiled, null, 2)};
`;

writeFileSync(outFile, header, 'utf8');
console.log(`\nWrote ${outFile}`);
