export type Action =
  // File
  | "create"
  | "open"
  // Code
  | "insert"
  | "highlight"
  | "replace"
  | "unselect"
  | "remove"
  | "delete"
  // Timeout
  | "waitForTimeout"
  | "waitForInput"
  // VSCode
  | "executeVSCodeCommand"
  | "showInfoMessage"
  // Terminal
  | "executeTerminalCommand";
