export type Action =
  // File
  | "create"
  | "open"
  | "rename"
  | "deleteFile"
  | "close"
  | "closeAll"
  // Markdown
  | "markdownPreview"
  // Code
  | "insert"
  | "highlight"
  | "replace"
  | "unselect"
  | "delete"
  | "positionCursor"
  | "write"
  | "save"
  // Settings
  | "setSetting"
  // Timeout
  | "waitForTimeout"
  | "waitForInput"
  // VSCode
  | "executeVSCodeCommand"
  | "showInfoMessage"
  // Terminal
  | "executeTerminalCommand"
  // Extensibility
  | "snippet";
