name: PR Checks

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "npm"

      - run: npm ci --legacy-peer-deps
      - uses: nrwl/nx-set-shas@v6

      # - run: npx nx start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      - run: npx nx-cloud record -- npx nx format:check
      - run: npx nx affected -t lint test
      - run: npx nx fix-ci
        if: always()
